cc_library(
    name = "convopt",
    srcs = [
        "convopt.cpp",
    ],
    hdrs = [
        "convopt.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/dualnumbers",
        "//src/spaces",
    ],
)
