load("//bazel:rules.bzl", "opt_cc_test")

opt_cc_test(
    name = "dualnumbers",
    size = "small",
)

opt_cc_test(
    name = "spaces",
    size = "small",
)

opt_cc_test(
    name = "convopt",
    size = "small",
)
