load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "dualnumbers",
    size = "small",
    srcs = ["dualnumbers_test.cpp"],
    deps = [
        "//:optimizer",
        "@ut",
    ],
)

cc_test(
    name = "spaces",
    size = "small",
    srcs = ["spaces_test.cpp"],
    deps = [
        "//:optimizer",
        "@ut",
    ],
)

cc_test(
    name = "convopt",
    size = "small",
    srcs = ["convopt_test.cpp"],
    deps = [
        "//:optimizer",
        "@ut",
    ],
)
