load("//bazel:rules.bzl", "opt_cc_test")

opt_cc_test(
    name = "dualnumbers",
    size = "small",
)

opt_cc_test(
    name = "math",
    size = "small",
)

opt_cc_test(
    name = "spaces",
    size = "small",
)

opt_cc_test(
    name = "spaces_ops",
    size = "small",
)

opt_cc_test(
    name = "matrix",
    size = "small",
)

opt_cc_test(
    name = "matrix_ops",
    size = "small",
)

opt_cc_test(
    name = "norms",
    size = "small",
)

opt_cc_test(
    name = "lineq_solvers",
    size = "small",
)

opt_cc_test(
    name = "convopt",
    size = "small",
)

opt_cc_test(
    name = "stdx_traits",
    size = "small",
)
