cc_library(
    name = "dualnumbers",
    srcs = [
        "dualnumbers.cpp",
    ],
    hdrs = [
        "dualnumbers.hpp",
        "math.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
